version: '3'

services:
  web:
    build: web
    ports:
      - "3000:3000"
      - "3035:3035"
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && ./bin/server"
    volumes:
      - ./web:/app
      - bundle:/usr/local/bundle
      - /app/node_modules
      - /app/vendor
    environment:
      - WEBPACKER_DEV_SERVER_HOST=web
    depends_on:
      - db
    tty: true
    stdin_open: true
  provider:
    build: provider
    ports:
      - "3001:3001"
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./provider:/app
      - bundle:/usr/local/bundle
      - /app/node_modules
      - /app/vendor
    depends_on:
      - db
  db:
    build: web/db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3307'
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
    - 6379:6379
    volumes:
    - redis:/data
    command: redis-server --appendonly yes

volumes:
  bundle:
  mysql_data:
  redis:
